### PR TITLE
[MaterialButton] Fixed issue 531 by removing unnecessary calls to set compound drawables

### LINKED ISSUE #531: [MaterialButton] Icon animated selector doesn't play if setting text
**Description:** If an animated state selector is used as the icon on the MaterialButton then the animation will play between states, but only if not also setting the text on the button (or anything that triggers updateIconPosition).

**Expected behavior:** The animation of the icon should play whether or not the text is set. This is the behaviour of AppCompatButton/Button.

**Source code:** Attached sample app demonstrating the issue.
[issue.zip](https://github.com/material-components/material-components-android/files/3531136/issue.zip)

**Android API version:** 28

**Material Library version:** 1.1.0-alpha09

**Device:** Emulator

### PR DESCRIPTION
**Pull request by samruston**
Closes #531 

Unnecessary calls to setCompoundDrawablesRelative caused animated state list drawables to be interrupted. If there were a checkable MaterialButton with an animated state list drawable as the icon and you also changed the text of the button then the animation wouldn't play. This PR fixes it by first checking if the compound drawables are already in the right configuration before setting it.

### CODE REVIEW

File: lib/java/com/google/android/material/button/MaterialButton.java [hunk 1]
```diff
@@ -663,9 +663,15 @@ private void updateIcon() {
...
 
-    if (iconGravity == ICON_GRAVITY_START || iconGravity == ICON_GRAVITY_TEXT_START) {
+    // Only update the icon position if it has changed
+    boolean iconStart = iconGravity == ICON_GRAVITY_START || iconGravity == ICON_GRAVITY_TEXT_START;
+    Drawable[] existingDrawables = TextViewCompat.getCompoundDrawablesRelative(this);
+    boolean hasDrawableStart = existingDrawables[0] != null;
+    boolean hasDrawableEnd = existingDrawables[2] != null;
+
+    if (iconStart && !hasDrawableStart) {
       TextViewCompat.setCompoundDrawablesRelative(this, icon, null, null, null);
```
Comment (wcshi) [inline lib/java/com/google/android/material/button/MaterialButton.java]: If icon is different from the existing start/end drawable, this update should happen

Comment (samruston) [reply lib/java/com/google/android/material/button/MaterialButton.java]: @wcshi Woops, my bad, was too concerned with the positioning. Fixed.

File: lib/java/com/google/android/material/button/MaterialButton.java [hunk 2]
```diff
@@ -663,7 +663,18 @@ private void updateIcon() {
       icon.setBounds(iconLeft, 0, iconLeft + width, height);
     }
 
-    if (iconGravity == ICON_GRAVITY_START || iconGravity == ICON_GRAVITY_TEXT_START) {
+    // Only update if the icon or the position has changed
+    boolean iconStart = iconGravity == ICON_GRAVITY_START || iconGravity == ICON_GRAVITY_TEXT_START;
```
[the remark this answers is not in the document]
Comment (samruston) [reply lib/java/com/google/android/material/button/MaterialButton.java]: Changed.

**Comment by samruston** [comment]
> Maybe let's add a test to https://github.com/material-components/material-components-android/blob/master/lib/javatests/com/google/android/material/button/MaterialButtonTest.java
> 
> This or make any changes you like:
> 
> ```java
>  @Test
>   public void setIcon_IconUpdated_whenCalledTwice() {
>     MaterialButton materialButton = new MaterialButton(context);
>     materialButton.setText("test");
>     int measureSpec =
>         MeasureSpec.makeMeasureSpec(200, MeasureSpec.AT_MOST);
> 
>     Drawable drawable1 = ContextCompat.getDrawable(context, android.R.drawable.btn_plus);
>     materialButton.setIcon(drawable1);
>     materialButton.setIconGravity(MaterialButton.ICON_GRAVITY_START);
>     materialButton.measure(measureSpec, measureSpec);
> 
>     assertThat(materialButton.getIcon()).isEqualTo(drawable1);
> 
>     Drawable drawable2 = ContextCompat.getDrawable(context, android.R.drawable.btn_minus);
>     materialButton.setIcon(drawable2);
>     materialButton.measure(measureSpec, measureSpec);
> 
>     assertThat(materialButton.getIcon()).isEqualTo(drawable2);
>   }
> ```
> 
> Note: I use real drawables cause we cannot mock drawable and other android classes internally.

Added the test as well.
